-- Durable ordering for account events makes equal-time marks, fills and
-- session boundaries replayable after the account snapshot is compacted.
ALTER TABLE paper_funded_event
  ADD COLUMN IF NOT EXISTS event_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY;
-- Rows that predate this migration receive an identity value for indexing but
-- cannot prove equal-time application order. New ledger writes opt into the
-- verified path explicitly; reports fail closed when an old row is required.
ALTER TABLE paper_funded_event
  ADD COLUMN IF NOT EXISTS event_sequence_verified BOOLEAN NOT NULL DEFAULT FALSE;

CREATE UNIQUE INDEX IF NOT EXISTS paper_funded_event_sequence_uq
  ON paper_funded_event(account_id,event_sequence);

-- A completed funded run owns an immutable economic boundary. Legacy runs are
-- intentionally not backfilled: their exact boundary cannot be proven from a
-- current account snapshot.
CREATE TABLE paper_funded_run_snapshot (
  run_id UUID PRIMARY KEY REFERENCES paper_bot_run(id),
  account_id UUID NOT NULL REFERENCES paper_funded_account(id),
  boundary_at TIMESTAMPTZ NOT NULL,
  state JSONB NOT NULL,
  orders JSONB NOT NULL,
  captured_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (state->>'version' = 'funded-ledger-v1'),
  CHECK (jsonb_typeof(orders) = 'array')
);

-- Order states are terminal snapshots, so retain each fact-time version for
-- explicit in-session reporting instead of reading a later current state.
ALTER TABLE paper_entry_order
  ADD COLUMN IF NOT EXISTS last_fact_at TIMESTAMPTZ;

UPDATE paper_entry_order
SET last_fact_at = COALESCE(last_fact_at, (submission->>'submittedAt')::timestamptz, updated_at)
WHERE last_fact_at IS NULL;

ALTER TABLE paper_entry_order
  ALTER COLUMN last_fact_at SET NOT NULL;

CREATE TABLE paper_entry_order_history (
  order_id TEXT NOT NULL REFERENCES paper_entry_order(order_id),
  revision BIGINT NOT NULL CHECK (revision >= 0),
  fact_at TIMESTAMPTZ NOT NULL,
  state JSONB NOT NULL,
  PRIMARY KEY(order_id,revision)
);

INSERT INTO paper_entry_order_history(order_id,revision,fact_at,state)
SELECT order_id,revision,last_fact_at,state
FROM paper_entry_order
ON CONFLICT(order_id,revision) DO NOTHING;

CREATE OR REPLACE FUNCTION capture_paper_entry_order_history() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO paper_entry_order_history(order_id,revision,fact_at,state)
  VALUES(NEW.order_id,NEW.revision,NEW.last_fact_at,NEW.state)
  ON CONFLICT(order_id,revision) DO UPDATE
    SET fact_at=EXCLUDED.fact_at,state=EXCLUDED.state;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS capture_paper_entry_order_history
  ON paper_entry_order;
CREATE TRIGGER capture_paper_entry_order_history
AFTER INSERT OR UPDATE OF state,last_fact_at,revision ON paper_entry_order
FOR EACH ROW EXECUTE FUNCTION capture_paper_entry_order_history();

INSERT INTO foundation_schema_version(version,description)
VALUES(79,'Funded temporal reporting boundaries and fact-time order history')
ON CONFLICT(version) DO NOTHING;
